Auto commit from[/usr/local/bin/save-work]

diff --git a/tools/adb-cp b/tools/adb-cp
--- a/tools/adb-cp
+++ b/tools/adb-cp
@@ -2,6 +2,8 @@
 
 #docker_id="/sdcard"
 docker_id="/data/local/tmp"
+adb="adb"
+
 main() {
 	local one_obj="$1"
 	local two_obj="$2"
@@ -29,5 +31,53 @@ main() {
 		adb pull "$docker_tar" "$local_tar"
 	fi
 }
+
+usage() {
+	echo "Usage :  $(basename "$0") [options] [--] argument-1 argument-2
+
+  Options:
+  -h, --help                  Display this message
+  -d, --debug                 Debug model run
+  -p, --posix                 Posix model parse shell command
+  -v, --version               Display script version
+  -f, --file FILE             Target file 
+  -D, --directory DIRECTORY   Target directory"
+
+}
+
+while getopts ":hdevf:D:-:" opt; do
+	case "${opt}" in
+	h) usage && exit 0 ;;
+	d) adb="adb -d" ;;
+	e) adb="adb -e" ;;
+	v)
+		echo "$0 -- Version $ScriptVersion"
+		exit
+		;;
+	f) file=${OPTARG} ;;
+	D) directory=${OPTARG} ;;
+	-) case "${OPTARG}" in
+		help) usage && exit 0 ;;
+		debug) set -x ;;
+		posix) set -o posix ;;
+		version)
+			echo "$0 -- Version $ScriptVersion"
+			exit
+			;;
+		file)
+			file=${!OPTIND}
+			OPTIND=$((OPTIND + 1))
+			;;
+		directory)
+			directory=${!OPTIND}
+			OPTIND=$((OPTIND + 1))
+			;;
+		*) echo "Invalid option: --${OPTARG}" >&2 && exit 1 ;;
+		esac ;;
+	:) echo "Option -${OPTARG} requires an argument." >&2 && exit 1 ;;
+	*) echo "Invalid option: -${OPTARG}" >&2 && exit 1 ;;
+	esac
+done
+shift $((OPTIND - 1))
 
 main "$@"
