给每个tools/.sh文件都添加set -e参数

diff --git a/tools/docker-attach b/tools/docker-attach
--- a/tools/docker-attach
+++ b/tools/docker-attach
@@ -1,4 +1,7 @@
 #!/bin/bash
+
+set -e
+
 ScriptVersion="1.0"
 
 docker_history="$HOME/.docker_history"
@@ -7,68 +10,70 @@ unset docker_id
 docker_status="stop"
 
 case "$(uname)" in
-	"Darwin") docker="docker";;
-	"Linux") docker="docker";;
-	*)echo "Windows has not been tested for the time being";exit 1
+"Darwin") docker="docker" ;;
+"Linux") docker="docker" ;;
+*)
+	echo "Windows has not been tested for the time being"
+	exit 1
+	;;
 esac
 
-main(){
-	if [ ! $docker_id ];then
+main() {
+	if [ ! $docker_id ]; then
 		try_fetch_docker_id
 	fi
-	if [ -z "$docker_id" ];then
+	if [ -z "$docker_id" ]; then
 		echo -e "\033[31m Need CONTAINER_ID\033[0m"
 		local tmp=$(${docker} ps -l | sed -n 2p)
-		if [ -z "$tmp" ];then
+		if [ -z "$tmp" ]; then
 			exit
 		fi
 		docker_id=$(echo "$tmp" | awk '{print $1}')
 		local docker_name=$(echo "$tmp" | awk '{print $2}')
 		read -p " Maybe you're looking for \"$docker_id $docker_name\" ? [Y/n]" ok
-		if [ "$ok" == "n" ];then
+		if [ "$ok" == "n" ]; then
 			exit
 		fi
 		docker_status="stop"
 	fi
-	if [ "$docker_status" == "running" ];then
-		echo $docker_id > $docker_history
+	if [ "$docker_status" == "running" ]; then
+		echo $docker_id >$docker_history
 		${docker} attach $docker_id
-	elif [ "$docker_status" == "stop" ];then
-		echo $docker_id > $docker_history
+	elif [ "$docker_status" == "stop" ]; then
+		echo $docker_id >$docker_history
 		${docker} start $docker_id && ${docker} attach $docker_id
 	else
-		echo -e "\033[31m Container status error -> $docker_status \033[0m";
+		echo -e "\033[31m Container status error -> $docker_status \033[0m"
 		exit
 	fi
 }
 
-
-
-try_fetch_docker_id(){
+try_fetch_docker_id() {
 	#Check whether exist running container in local
 	local docker_count=$(${docker} ps | wc -l | sed 's/ //g')
-	if [ $docker_count == 1 ];then
+	if [ $docker_count == 1 ]; then
 		unset docker_id
-	elif [ $docker_count == 2 ];then
+	elif [ $docker_count == 2 ]; then
 		docker_id=$(${docker} ps | sed -n 2p | awk '{print $1}')
-	elif [ $docker_count -gt 2 ];then
-		echo -e "\033[31m Detection multiple container,need statement container id in command argument\033[0m";exit
+	elif [ $docker_count -gt 2 ]; then
+		echo -e "\033[31m Detection multiple container,need statement container id in command argument\033[0m"
+		exit
 	fi
 
 	#Found usable container
-	if [ -n "$docker_id" ];then
+	if [ -n "$docker_id" ]; then
 		docker_status="running"
 		return
 	fi
 
 	#Check history file whether exist container id
-	if [ -f $docker_history ];then
+	if [ -f $docker_history ]; then
 		docker_id=$(cat $docker_history)
 		docker_status="stop"
 	fi
 }
 
-usage (){
+usage() {
 	echo "Usage :  $(basename "$0") [options] [--] argument-1 argument-2
 
 	Options:
@@ -83,25 +88,37 @@ usage (){
 
 while getopts ":hdpvi:D:-:" opt; do
 	case "${opt}" in
-		h) usage && exit 0;;
-		d) set -x ;;
-		p) set -o posix ;;
-		v) echo "$0 -- Version $ScriptVersion"; exit ;;
-		i) docker_id=${OPTARG};;
-		D) directory=${OPTARG};;
-		-) case "${OPTARG}" in
-			help) usage && exit 0;;
-			debug)      set -x ;;
-			posix)      set -o posix ;;
-			version)    echo "$0 -- Version $ScriptVersion"; exit ;;
-			id)         docker_id=${!OPTIND}; OPTIND=$((OPTIND+1));;
-			directory)  directory=${!OPTIND}; OPTIND=$((OPTIND+1));;
-			*)          echo "Invalid option: --${OPTARG}" >&2 && exit 1;;
-		esac;;
-	:) echo "Option -${OPTARG} requires an argument." >&2 && exit 1;;
-	*) echo "Invalid option: -${OPTARG}" >&2 && exit 1;;
-esac
+	h) usage && exit 0 ;;
+	d) set -x ;;
+	p) set -o posix ;;
+	v)
+		echo "$0 -- Version $ScriptVersion"
+		exit
+		;;
+	i) docker_id=${OPTARG} ;;
+	D) directory=${OPTARG} ;;
+	-) case "${OPTARG}" in
+		help) usage && exit 0 ;;
+		debug) set -x ;;
+		posix) set -o posix ;;
+		version)
+			echo "$0 -- Version $ScriptVersion"
+			exit
+			;;
+		id)
+			docker_id=${!OPTIND}
+			OPTIND=$((OPTIND + 1))
+			;;
+		directory)
+			directory=${!OPTIND}
+			OPTIND=$((OPTIND + 1))
+			;;
+		*) echo "Invalid option: --${OPTARG}" >&2 && exit 1 ;;
+		esac ;;
+	:) echo "Option -${OPTARG} requires an argument." >&2 && exit 1 ;;
+	*) echo "Invalid option: -${OPTARG}" >&2 && exit 1 ;;
+	esac
 done
-shift $((OPTIND-1))
+shift $((OPTIND - 1))
 
 main "$@"
diff --git a/tools/docker-cp b/tools/docker-cp
--- a/tools/docker-cp
+++ b/tools/docker-cp
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -e
+
 ScriptVersion="1.0"
 
 unset local_tar
@@ -12,23 +14,26 @@ unset docker_id
 user="/home/hi"
 
 case "$(uname)" in
-  "Darwin") docker="docker";;
-  "Linux") docker="docker";;
-  *)echo "Windows has not been tested for the time being";exit 1
+"Darwin") docker="docker" ;;
+"Linux") docker="docker" ;;
+*)
+  echo "Windows has not been tested for the time being"
+  exit 1
+  ;;
 esac
 
-
-main(){
+main() {
   local one_obj="$1"
   local two_obj="$2"
 
-  if [ -z "$one_obj" ];then
-    echo -e "\033[31m Try --help\033[0m";exit
+  if [ -z "$one_obj" ]; then
+    echo -e "\033[31m Try --help\033[0m"
+    exit
   fi
 
   # 存在本地共享目录映射，自己通过简单的cp名了完成即可
-  if [ -d $HOME/docker-home ] || [ -d $HOME/Docker-home ] ;then
-    if [[ -f "$one_obj" || -d "$one_obj" ]];then
+  if [ -d $HOME/docker-home ] || [ -d $HOME/Docker-home ]; then
+    if [[ -f "$one_obj" || -d "$one_obj" ]]; then
       echo "cp -r" "${one_obj%/}" "$HOME/docker-home/"
       cp -r "${one_obj%/}" "$HOME/docker-home/"
     else
@@ -40,10 +45,10 @@ main(){
 
   try_fetch_docker_id
 
-  if [[ -f "$one_obj" || -d "$one_obj" ]];then
+  if [[ -f "$one_obj" || -d "$one_obj" ]]; then
     local_tar="$one_obj"
     docker_tar="${docker_id}:${two_obj}"
-    if [ -z "$two_obj" ];then
+    if [ -z "$two_obj" ]; then
       docker_tar="${docker_id}:/${user}"
     fi
     echo "docker cp \"$local_tar\" \"$docker_tar\""
@@ -51,7 +56,7 @@ main(){
   else
     docker_tar="${docker_id}:${one_obj}"
     local_tar="$two_obj"
-    if [ -z "$two_obj" ];then
+    if [ -z "$two_obj" ]; then
       local_tar="./"
     fi
     echo "docker cp \"$docker_tar\" \"$local_tar\""
@@ -59,21 +64,21 @@ main(){
   fi
 }
 
-
-
-try_fetch_docker_id(){
+try_fetch_docker_id() {
   #Check whether exist running container in local
   local docker_count=$(${docker} ps | wc -l | sed 's/ //g')
-  if [ $docker_count == 1 ];then
-    echo -e "\033[31m No container found \033[0m";exit
-  elif [ $docker_count == 2 ];then
+  if [ $docker_count == 1 ]; then
+    echo -e "\033[31m No container found \033[0m"
+    exit
+  elif [ $docker_count == 2 ]; then
     docker_id=$(${docker} ps | sed -n 2p | awk '{print $1}')
-  elif [ $docker_count -gt 2 ];then
-    echo -e "\033[31m Detection multiple container,need statement container id in command argument\033[0m";exit
+  elif [ $docker_count -gt 2 ]; then
+    echo -e "\033[31m Detection multiple container,need statement container id in command argument\033[0m"
+    exit
   fi
 }
 
-usage (){
+usage() {
   echo "Usage :  $(basename "$0") [options] [--] path-one [path-two]
 
   Such as ->
@@ -90,25 +95,31 @@ usage (){
     -p, --posix                 Posix model parse shell command
     -v, --version               Display script version"
 
-  }
+}
 
-  while getopts ":hdpvi:D:-:" opt; do
-    case "${opt}" in
-      h) usage && exit 0;;
-      d) set -x ;;
-      p) set -o posix ;;
-      v) echo "$0 -- Version $ScriptVersion"; exit ;;
-      -) case "${OPTARG}" in
-        help) usage && exit 0;;
-        debug)      set -x ;;
-        posix)      set -o posix ;;
-        version)    echo "$0 -- Version $ScriptVersion"; exit ;;
-        *)          echo "Invalid option: --${OPTARG}" >&2 && exit 1;;
-      esac;;
-    :) echo "Option -${OPTARG} requires an argument." >&2 && exit 1;;
-    *) echo "Invalid option: -${OPTARG}" >&2 && exit 1;;
+while getopts ":hdpvi:D:-:" opt; do
+  case "${opt}" in
+  h) usage && exit 0 ;;
+  d) set -x ;;
+  p) set -o posix ;;
+  v)
+    echo "$0 -- Version $ScriptVersion"
+    exit
+    ;;
+  -) case "${OPTARG}" in
+    help) usage && exit 0 ;;
+    debug) set -x ;;
+    posix) set -o posix ;;
+    version)
+      echo "$0 -- Version $ScriptVersion"
+      exit
+      ;;
+    *) echo "Invalid option: --${OPTARG}" >&2 && exit 1 ;;
+    esac ;;
+  :) echo "Option -${OPTARG} requires an argument." >&2 && exit 1 ;;
+  *) echo "Invalid option: -${OPTARG}" >&2 && exit 1 ;;
   esac
 done
-shift $((OPTIND-1))
+shift $((OPTIND - 1))
 
 main "$@"
