Auto commit from[/usr/local/bin/save-work]

diff --git a/tools/start-latex-work b/tools/start-latex-work
--- a/tools/start-latex-work
+++ b/tools/start-latex-work
@@ -10,9 +10,9 @@ interrupt_counter=0
 open_math_env_webside=0
 is_tex=1
 
-check_parameter_legal(){
-  if [ -z "$file" ];then
-    if [ $1 ];then
+check_parameter_legal() {
+  if [ -z "$file" ]; then
+    if [ $1 ]; then
       file_type=${1##*.}
       if [[ "$file_type" == "md" || "$file_type" == "tex" ]]; then
         file="$1"
@@ -26,18 +26,18 @@ check_parameter_legal(){
     fi
   fi
 
-  #  替换为绝对路径 # 
+  #  替换为绝对路径 #
   file="$(realpath "$file")"
-  if [ $pdf ];then
+  if [ $pdf ]; then
     pdf="$(realpath "$pdf")"
   fi
 }
 
-main_Ubuntu(){
-  if [ -n "$(pgrep zathura)" ];then
-    echo -e "\033[31m检测到后台存在zathura窗口，需要关闭全部窗口再启动，是否关闭？[y/N] \033[0m"
+main_Ubuntu() {
+  if [ -n "$(pgrep zathura)" ]; then
+    echo -e "\033[31m检测到后台存在zathura窗口，需要关闭全部窗口再启动，是否关闭？[Y/n] \033[0m"
     read ok
-    if [ "$ok" == y ];then
+    if [ "$ok" != n ]; then
       killall zathura
       sleep 1
     else
@@ -46,33 +46,35 @@ main_Ubuntu(){
   fi
 
   current_window_id=$(xdotool getactivewindow)
-  if [ ! $current_window_id ];then #如果是后台启动的会有无窗口的情况
+  if [ ! $current_window_id ]; then #如果是后台启动的会有无窗口的情况
     current_window_id=$(wmctrl -lp | grep $(pgrep terminator) | awk '{print $1}')
     #这里使用SHELL名字来获取进程，不知道会不会有问题
     find_windows_id_line_count=$(echo "$current_window_id" | wc -l)
-    if [ $find_windows_id_line_count -gt 1 ];then
-      echo -e "\033[31mterminator存在多个窗口($find_windows_id_line_count)，关闭全部窗口，再试~\033[0m";exit 
-    elif [ ! "$current_window_id" ];then
-      echo -e "\033[31m未找到terminal id\033[0m";exit
+    if [ $find_windows_id_line_count -gt 1 ]; then
+      echo -e "\033[31mterminator存在多个窗口($find_windows_id_line_count)，关闭全部窗口，再试~\033[0m"
+      exit
+    elif [ ! "$current_window_id" ]; then
+      echo -e "\033[31m未找到terminal id\033[0m"
+      exit
     fi
   fi
   gnome-extensions disable ubuntu-dock@ubuntu.com
   gnome-extensions enable gtktitlebar@velitasali.github.io
 
-  if [ $pdf ];then
+  if [ -n $pdf ]; then
     #open pdf into Upper right corner
-    zathura "${pdf}" 2> /dev/null &
+    zathura "${pdf}" 2>/dev/null &
     zathura_pdf_pid=$!
     #echo "zathura 已在后台执行 pid为 $zathura_pdf_pid"
 
     #等待窗口完全加载
-    while true;do
-      if [ "$(ps -p $zathura_pdf_pid -o comm=)" == "zathura" ];then
+    while true; do
+      if [ "$(ps -p $zathura_pdf_pid -o comm=)" == "zathura" ]; then
         sleep 0.5
         break
       fi
       let interrupt_counter+=1
-      if [[ $interrupt_counter > 100 ]];then
+      if [[ $interrupt_counter > 100 ]]; then
         exit
       fi
     done
@@ -86,51 +88,50 @@ main_Ubuntu(){
   {
     sleep 1.5
 
-    while true;do
-      if [ $zathura_pdf_pid ];then
-        zathura_tex_show_id=$(wmctrl -lp | grep $(pgrep zathura | grep -v $zathura_pdf_pid 2> /dev/null) 2> /dev/null | awk '{print $1}')
+    while true; do
+      if [ -n $zathura_pdf_pid ]; then
+        zathura_tex_show_id=$(wmctrl -lp | grep $(pgrep zathura | grep -v $zathura_pdf_pid 2>/dev/null) 2>/dev/null | awk '{print $1}')
       else
-        zathura_tex_show_id=$(wmctrl -lp | grep $(pgrep zathura) 2> /dev/null | awk '{print $1}')
+        zathura_tex_show_id=$(wmctrl -lp | grep $(pgrep zathura) 2>/dev/null | awk '{print $1}')
       fi
-      if [ $zathura_tex_show_id ];then
+      if [ -n $zathura_tex_show_id ]; then
         break
       fi
       sleep 0.5
       let interrupt_counter+=1
-      if [[ $interrupt_counter > 100 ]];then
+      if [[ $interrupt_counter > 100 ]]; then
         exit
       fi
     done
     #echo -e "找到zathura_tex_show_id: $zathura_tex_show_id"
     xdotool windowactivate $zathura_tex_show_id && $linux_keyboard_file -l -p 1
 
-    if [ "$open_math_env_webside" == "1" ];then
+    if [ "$open_math_env_webside" == "1" ]; then
       google-chrome https://bing.com/chat https://zs.symbolab.com/solver
     fi
 
     #焦点回给到vim进行代码编辑
     xdotool windowactivate $current_window_id
-  }&
+  } &
 
-  if [ $pdf ];then
+  if [ -n $pdf ]; then
     xdotool windowactivate $current_window_id && $linux_keyboard_file -k -p 1
   else
     xdotool windowactivate $current_window_id && $linux_keyboard_file -r -p 1
   fi
-  if [ $is_tex == 1 ];then
-    nvim -c "execute 'VimtexCompile' | execute 'lua require(\"notify\")(\"Welcome to Math\")'" $file 
+  if [ $is_tex == 1 ]; then
+    nvim -c "execute 'VimtexCompile' | execute 'lua require(\"notify\")(\"Welcome to Math\")'" $file
     #这里阻塞了，执行到上面nvim就阻塞了
   fi
 
   quit
 }
 
-
-main_Mac(){
+main_Mac() {
   check_foot_py_file_exitst
   osascript -e 'tell application "System Events" to tell dock preferences to set autohide to true'
 
-  if [ $pdf ];then
+  if [ $pdf ]; then
     #open pdf into Upper right corner
     open ${pdf}
     sleep 0.1
@@ -147,14 +148,14 @@ main_Mac(){
 
   #vim into Down right corner
   osascript -e 'tell application "iTerm2" to activate'
-  if [ $pdf ];then
+  if [ $pdf ]; then
     osascript -e 'tell application "System Events"
     key down {control, option}
     key code 40
     key up {control, option}
   end tell'
-else
-  osascript -e 'tell application "System Events"
+  else
+    osascript -e 'tell application "System Events"
   key down {control, option}
   key code 124
   key up {control, option}
@@ -163,21 +164,21 @@ end tell'
 
   {
     #sleep 0.2
-    if [ $is_tex == 1 ];then
+    if [ $is_tex == 1 ]; then
       osascript -e 'tell application "System Events"
       if not (exists process "Skim") then
         tell application "Skim" to activate
       end if
     end tell'
-  else
-    osascript -e 'tell application "System Events"
+    else
+      osascript -e 'tell application "System Events"
     if not (exists process "Google Chrome") then
       tell application "Google Chrome" to activate
     end if
   end tell'
     fi
 
-    if [ $is_tex == 1 ];then
+    if [ $is_tex == 1 ]; then
       osascript -e 'tell application "Skim" to activate'
     else
       osascript -e 'tell application "Google Chrome" to activate'
@@ -189,59 +190,59 @@ end tell'
     key up {control, option}
   end tell'
 
-  if [ $is_tex == 1 ];then
-    osascript -e 'tell application "System Events"
+    if [ $is_tex == 1 ]; then
+      osascript -e 'tell application "System Events"
     key down {command, shift}
     key code 15
     key up {command, shift}
   end tell'
+    fi
+
+    osascript -e 'tell application "iTerm2" to activate'
+  } &
+
+  if [ $is_tex == 1 ]; then
+    nvim -c "execute 'VimtexCompile' | execute 'lua require(\"notify\")(\"Welcome to Math\")'" $file
+  else
+    nvim -c 'MarkdownPreview' "$file"
   fi
 
+  quit
+
   osascript -e 'tell application "iTerm2" to activate'
-}&
-
-if [ $is_tex == 1 ];then
-  nvim -c "execute 'VimtexCompile' | execute 'lua require(\"notify\")(\"Welcome to Math\")'" $file
-else
-  nvim -c 'MarkdownPreview' "$file"
-fi
-
-quit
-
-osascript -e 'tell application "iTerm2" to activate'
-osascript -e 'tell application "System Events"
+  osascript -e 'tell application "System Events"
 key down {control, option}
 key code 124
 key up {control, option}
 end tell'
 
-if [ $is_tex == 1 ];then
-  osascript -e 'tell application "Skim" to activate'
-else
-  osascript -e 'tell application "Google Chrome" to activate'
-fi
-osascript -e 'tell application "System Events"
+  if [ $is_tex == 1 ]; then
+    osascript -e 'tell application "Skim" to activate'
+  else
+    osascript -e 'tell application "Google Chrome" to activate'
+  fi
+  osascript -e 'tell application "System Events"
 key down {control, option}
 key code 123
 key up {control, option}
 end tell'
 
-#get focus to iTerm2
-osascript -e 'tell application "iTerm2" to activate'
+  #get focus to iTerm2
+  osascript -e 'tell application "iTerm2" to activate'
 }
 
-check_foot_py_file_exitst(){
-  if [ ! -f ${keyboard_file} ];then
-    echo "IyEvdXNyL2Jpbi9lbnYgcHl0aG9uCiMgLSotIGNvZGluZzogVVRGLTggLSotCmZyb20gcHlrZXlib2FyZCBpbXBvcnQgKgpmcm9tIHB5bW91c2UgaW1wb3J0ICoKZnJvbSBzeXMgaW1wb3J0ICoKCm0gPSBQeU1vdXNlKCkKayA9IFB5S2V5Ym9hcmQoKQoKCmlmIChzeXMuYXJndlsxXSA9PSAiQy10YWIiKToKICAgIHhfZGltLCB5X2RpbSA9IG0uc2NyZWVuX3NpemUoKQogICAgay5wcmVzc19rZXlzKFsnQ29tbWFuZCcsJ1RhYiddKQplbGlmIChzeXMuYXJndlsxXSA9PSAibWFyayIpOgogICAgay5wcmVzc19rZXlzKFsnYCcsJy4nXSkKZWxzZToKICAgIGsucHJlc3Nfa2V5cyhbJ0NvbnRyb2wnLCdBbHRlcm5hdGUnLHN5cy5hcmd2WzFdXSkKICAgIGsucmVsZWFzZV9rZXkoJ0NvbnRyb2wnKQogICAgay5yZWxlYXNlX2tleSgnQWx0ZXJuYXRlJykKICAgIGsucmVsZWFzZV9rZXkoc3lzLmFyZ3ZbMV0pCgoj54K55Ye75Lit5b+DCiNtLmNsaWNrKHhfZGltLzIrMTAwLCB5X2RpbS8yKzEwMCkKI+i+k+WFpeWtl+espgojay50eXBlX3N0cmluZygnOk1hcmtkb3duUHJldmlldycpCiPmjInkvY8KI2sucHJlc3Nfa2V5KCdDb21tYW5kJykKI+WNleWHuwojay50YXBfa2V5KCdjJykK" | base64 -d > ./${keyboard_file} && chmod +x ./${keyboard_file}
+check_foot_py_file_exitst() {
+  if [ ! -f ${keyboard_file} ]; then
+    echo "IyEvdXNyL2Jpbi9lbnYgcHl0aG9uCiMgLSotIGNvZGluZzogVVRGLTggLSotCmZyb20gcHlrZXlib2FyZCBpbXBvcnQgKgpmcm9tIHB5bW91c2UgaW1wb3J0ICoKZnJvbSBzeXMgaW1wb3J0ICoKCm0gPSBQeU1vdXNlKCkKayA9IFB5S2V5Ym9hcmQoKQoKCmlmIChzeXMuYXJndlsxXSA9PSAiQy10YWIiKToKICAgIHhfZGltLCB5X2RpbSA9IG0uc2NyZWVuX3NpemUoKQogICAgay5wcmVzc19rZXlzKFsnQ29tbWFuZCcsJ1RhYiddKQplbGlmIChzeXMuYXJndlsxXSA9PSAibWFyayIpOgogICAgay5wcmVzc19rZXlzKFsnYCcsJy4nXSkKZWxzZToKICAgIGsucHJlc3Nfa2V5cyhbJ0NvbnRyb2wnLCdBbHRlcm5hdGUnLHN5cy5hcmd2WzFdXSkKICAgIGsucmVsZWFzZV9rZXkoJ0NvbnRyb2wnKQogICAgay5yZWxlYXNlX2tleSgnQWx0ZXJuYXRlJykKICAgIGsucmVsZWFzZV9rZXkoc3lzLmFyZ3ZbMV0pCgoj54K55Ye75Lit5b+DCiNtLmNsaWNrKHhfZGltLzIrMTAwLCB5X2RpbS8yKzEwMCkKI+i+k+WFpeWtl+espgojay50eXBlX3N0cmluZygnOk1hcmtkb3duUHJldmlldycpCiPmjInkvY8KI2sucHJlc3Nfa2V5KCdDb21tYW5kJykKI+WNleWHuwojay50YXBfa2V5KCdjJykK" | base64 -d >./${keyboard_file} && chmod +x ./${keyboard_file}
   fi
 }
 
-use_history_info(){
+use_history_info() {
   file=$(cat $study_database_file | tail -1 | awk '{print $3}')
   pdf=$(cat $study_database_file | tail -1 | awk '{print $4}')
 }
 
-usage (){
+usage() {
   echo "Usage :  $(basename "$0") [options] [--] argument-1 argument-2
 
   Options:
@@ -252,8 +253,8 @@ usage (){
   -f, --file FILE  Test input argument"
 }
 
-quit(){
-  if [ "$(uname)" == "Linux" ];then
+quit() {
+  if [ "$(uname)" == "Linux" ]; then
     gnome-extensions enable ubuntu-dock@ubuntu.com
     gnome-extensions disable gtktitlebar@velitasali.github.io
   else
@@ -261,46 +262,68 @@ quit(){
   fi
   colse_study_date=$(date +"%Y-%m-%d-%H:%M:%S")
 
-  if [ ! -f $study_database_file ];then
-    echo "开始学习时间 结束学习时间 所编写的文件 所使用的PDF" > $study_database_file
+  if [ ! -f $study_database_file ]; then
+    echo "开始学习时间 结束学习时间 所编写的文件 所使用的PDF" >$study_database_file
   fi
-  echo "$start_study_date $colse_study_date $file $pdf" >> $study_database_file
+  echo "$start_study_date $colse_study_date $file $pdf" >>$study_database_file
   #  TODO YangJing 如果file,pdf中包含空格的情况 <24-03-24 00:06:27> #
 }
 
 while getopts ":hdp:vf:q-:" opt; do
   case "${opt}" in
-    h) usage && exit 0;;
-    d) set -x ;;
-    p) pdf=${OPTARG};;
-    v) echo "$0 -- Version $ScriptVersion"; exit ;;
-    f) file=${OPTARG};;
-    q) quit; exit;;
-    -) case "${OPTARG}" in
-      help) usage && exit 0;;
-      debug)    set -x ;;
-      pdf)      pdf=${!OPTIND}; OPTIND=$((OPTIND+1));;
-      env)      open_math_env_webside=1; OPTIND=$((OPTIND+1));;
-      version)  echo "$0 -- Version $ScriptVersion"; exit ;;
-      file)     echo "file=${!OPTIND}"; OPTIND=$((OPTIND+1));;
-      history)  use_history_info;;
-      quit)     quit; exit;;
-      *) echo "Invalid option: --${OPTARG}" >&2 && exit 1;;
-    esac;;
-  :) echo "Option -${OPTARG} requires an argument." >&2 && exit 1;;
-  *) echo "Invalid option: -${OPTARG}" >&2 && exit 1;;
-esac
+  h) usage && exit 0 ;;
+  d) set -x ;;
+  p) pdf=${OPTARG} ;;
+  v)
+    echo "$0 -- Version $ScriptVersion"
+    exit
+    ;;
+  f) file=${OPTARG} ;;
+  q)
+    quit
+    exit
+    ;;
+  -) case "${OPTARG}" in
+    help) usage && exit 0 ;;
+    debug) set -x ;;
+    pdf)
+      pdf=${!OPTIND}
+      OPTIND=$((OPTIND + 1))
+      ;;
+    env)
+      open_math_env_webside=1
+      OPTIND=$((OPTIND + 1))
+      ;;
+    version)
+      echo "$0 -- Version $ScriptVersion"
+      exit
+      ;;
+    file)
+      echo "file=${!OPTIND}"
+      OPTIND=$((OPTIND + 1))
+      ;;
+    history) use_history_info ;;
+    quit)
+      quit
+      exit
+      ;;
+    *) echo "Invalid option: --${OPTARG}" >&2 && exit 1 ;;
+    esac ;;
+  :) echo "Option -${OPTARG} requires an argument." >&2 && exit 1 ;;
+  *) echo "Invalid option: -${OPTARG}" >&2 && exit 1 ;;
+  esac
 done
-shift $((OPTIND-1))
+shift $((OPTIND - 1))
 
 check_parameter_legal "$@"
 
-if [ ! -f $file ];then
-  echo -e "\033[31mNot fond $file\033[0m";exit
+if [ ! -f $file ]; then
+  echo -e "\033[31mNot fond $file\033[0m"
+  exit
 fi
 
 start_study_date=$(date +"%Y-%m-%d-%H:%M:%S")
-if [ "$(uname)" == "Linux" ];then
+if [ "$(uname)" == "Linux" ]; then
   main_Ubuntu "$@"
 else
   main_Mac "$@"
diff --git a/tools/ubuntu_move_windows b/tools/ubuntu_move_windows
--- a/tools/ubuntu_move_windows
+++ b/tools/ubuntu_move_windows
@@ -12,23 +12,33 @@
 #`wmctrl -r :ACTIVE: -e 0,0,0,500,500`这个命令会将当前活动的窗口移动到屏幕的左上角，并将窗口的大小设置为500x500。
 #
 ScriptVersion="1.0"
+#set -x
 
 unset key
 unset file
 unset directory
 screen_info_file=$HOME/.screen_info
 
-init_info(){
+convert_to_int() {
+	local n=$1
+	if [ -z $n ]; then
+		echo 0
+	else
+		echo $n
+	fi
+}
+
+init_info() {
 	wid=$(xwininfo -root | grep Width | awk '{print $2}')
 	hei=$(xwininfo -root | grep Height | awk '{print $2}')
 	#如果有多个屏幕，那么需要给每个屏幕都设置dock栏的显示，不然会有高度计算不准的情况
 
-	screen_count=$(xrandr 2>/dev/null | grep ' connected' | wc -l )
-	if [ $screen_count == "1" ];then
+	screen_count=$(xrandr 2>/dev/null | grep ' connected' | wc -l)
+	if [ $screen_count == "1" ]; then
 		#如果是一个屏幕则不需要进一步判断
 		half_wid=$(expr $wid / 2)
 		half_hei=$(expr $hei / 2)
-	elif [ $screen_count == "2" ];then
+	elif [ $screen_count == "2" ]; then
 		#如果是两个屏幕,先获取主屏幕的宽高
 		primary_screen_info=$(xrandr 2>/dev/null | grep ' connected' | grep 'primary')
 		primary_screen_width=$(echo $primary_screen_info | awk '{print $4}' | awk -F "x" '{print $1}')
@@ -37,7 +47,7 @@ init_info(){
 		secondary_screen_info=$(xrandr 2>/dev/null | grep ' connected' | grep -v 'primary')
 		secondary_screen_width=$(echo $secondary_screen_info | awk '{print $3}' | awk -F "x" '{print $1}')
 		secondary_screen_height=$(echo $secondary_screen_info | awk '{print $3}' | awk -F "x" '{print $2}' | awk -F "+" '{print $1}')
-		if [ $primary_screen_width == $secondary_screen_width ] && [ $primary_screen_height == $secondary_screen_height ];then
+		if [ $primary_screen_width == $secondary_screen_width ] && [ $primary_screen_height == $secondary_screen_height ]; then
 			#如果两个屏幕的分辨率是一样的
 			half_wid=$(expr $wid / 4)
 			half_hei=$(expr $hei / 2)
@@ -47,21 +57,22 @@ init_info(){
 			#			half_hei=$(expr $primary_screen_height / 2)
 		fi
 	else
-		echo "TODO 存在两个以上屏幕;";exit
+		echo "TODO 存在两个以上屏幕;"
+		exit
 	fi
 
-	echo all_width:$wid > $screen_info_file
-	echo all_height:$hei >> $screen_info_file
-	echo primary_screen_width:$primary_screen_width >> $screen_info_file
-	echo primary_screen_height:$primary_screen_height >> $screen_info_file
-	echo secondary_screen_width:$secondary_screen_width >> $screen_info_file
-	echo secondary_screen_height:$secondary_screen_height >> $screen_info_file
-	echo half_wid:$half_wid >> $screen_info_file
-	echo half_hei:$half_hei >> $screen_info_file
+	echo all_width:$(convert_to_int $wid) >$screen_info_file
+	echo all_height:$(convert_to_int $hei) >>$screen_info_file
+	echo primary_screen_width:$(convert_to_int $primary_screen_width) >>$screen_info_file
+	echo primary_screen_height:$(convert_to_int $primary_screen_height) >>$screen_info_file
+	echo secondary_screen_width:$(convert_to_int $secondary_screen_width) >>$screen_info_file
+	echo secondary_screen_height:$(convert_to_int $secondary_screen_height) >>$screen_info_file
+	echo half_wid:$(convert_to_int $half_wid) >>$screen_info_file
+	echo half_hei:$(convert_to_int $half_hei) >>$screen_info_file
 	cat $screen_info_file
 }
 
-read_database_info(){
+read_database_info() {
 	wid=$(cat $screen_info_file | grep all_width | awk -F ":" '{print $2}')
 	hei=$(cat $screen_info_file | grep all_height | awk -F ":" '{print $2}')
 	primary_screen_width=$(cat $screen_info_file | grep primary_screen_width | awk -F ":" '{print $2}')
@@ -77,62 +88,64 @@ read_database_info(){
 	#echo primary_screen_height:$primary_screen_height
 	#echo secondary_screen_width:$secondary_screen_width
 	#echo secondary_screen_height:$secondary_screen_height
-	#echo half_wid:$half_wid 
-	#echo half_hei:$half_hei 
+	#echo half_wid:$half_wid
+	#echo half_hei:$half_hei
 }
 
-check_current_position(){
+check_current_position() {
 	current_position=$(xdotool getactivewindow getwindowgeometry | grep "Position" | awk -F ": " '{print $2}' | awk -F "," '{print $1}')
 	#echo current_position:$current_position
 	offset=0
-	if [ $current_position -lt $primary_screen_width ];then
-		#  TODO YangJing 仅考虑副屏幕在主屏幕的左边的情况 <24-04-12 11:37:08> #
-		#在主屏
-		half_wid=$(expr $primary_screen_width / 2)
-		half_hei=$(expr $primary_screen_height / 2)
-	elif [ $current_position -gt $primary_screen_width ];then
-		#在副屏
-		half_wid=$(expr $secondary_screen_width / 2)
-		half_hei=$(expr $secondary_screen_height / 2)
-		offset=$(expr $primary_screen_width + 10)
+	if [ $primary_screen_width != 0 ]; then
+		if [ $current_position -le $primary_screen_width ]; then
+			#  TODO YangJing 仅考虑副屏幕在主屏幕的左边的情况 <24-04-12 11:37:08> #
+			#在主屏
+			half_wid=$(expr $primary_screen_width / 2)
+			half_hei=$(expr $primary_screen_height / 2)
+		elif [ $current_position -ge $primary_screen_width ]; then
+			#在副屏
+			half_wid=$(expr $secondary_screen_width / 2)
+			half_hei=$(expr $secondary_screen_height / 2)
+			offset=$(expr $primary_screen_width + 10)
+		fi
 	fi
 }
 windwos_name=":ACTIVE:"
 
-main(){
-	if [ ! -f $screen_info_file ];then
-		init_info
-	else
+main() {
+	if [ -f $screen_info_file ]; then
 		read_database_info
+	else
+		init_info
 	fi
 	check_current_position
 
 	#echo offset:$offset
-	if [ "$key" == "left" ];then
+	if [ "$key" == "left" ]; then
 		#置于左半屏幕
 		wmctrl -r $windwos_name -e 2,$offset,0,$half_wid,$hei
-	elif [ "$key" == "right" ];then
+	elif [ "$key" == "right" ]; then
 		#置于右半屏幕
 		wmctrl -r $windwos_name -e 2,$(expr $half_wid + $offset),0,$half_wid,$hei
-	elif [ "$key" == "u" ];then
+	elif [ "$key" == "u" ]; then
 		#置于左上屏幕
 		wmctrl -r $windwos_name -e 2,$offset,0,$half_wid,$half_hei
-	elif [ "$key" == "i" ];then
+	elif [ "$key" == "i" ]; then
 		#置于右上屏幕
 		wmctrl -r $windwos_name -e 2,$(expr $half_wid + $offset),0,$half_wid,$half_hei
-	elif [ "$key" == "j" ];then
+	elif [ "$key" == "j" ]; then
 		#置于左下屏幕
 		wmctrl -r $windwos_name -e 2,$offset,$half_hei,$half_wid,$half_hei
-	elif [ "$key" == "k" ];then
+	elif [ "$key" == "k" ]; then
 		#置于右下屏幕
 		wmctrl -r $windwos_name -e 2,$(expr $half_wid + $offset),$half_hei,$half_wid,$half_hei
-	elif [ "$key" == "top" ];then
+	elif [ "$key" == "top" ]; then
 		#置于上半屏幕
 		wmctrl -r $windwos_name -e 2,0,0,$wid,$half_hei
-	elif [ "$key" == "down" ];then
+	elif [ "$key" == "down" ]; then
 		#置于下半屏幕
 		wmctrl -r $windwos_name -e 2,0,$half_hei,$wid,$half_hei
-	elif [ "$key" == "center" ];then
+	elif [ "$key" == "center" ]; then
 		#居中屏幕
 		get_current_windows_size
 		#elif [ "$key" == "Max" ];then
@@ -141,14 +154,13 @@ main(){
 	fi
 }
 
-get_current_windows_size(){
+get_current_windows_size() {
 	windows_wid=$(xwininfo -id $(xdotool getactivewindow) | awk '/Width/ {print $2}')
 	windows_hei=$(xwininfo -id $(xdotool getactivewindow) | awk '/Height/ {print $2}')
-	wmctrl -r $windwos_name -e 2,$(expr $(expr $wid - $windows_wid ) / 2),$(expr $(expr $hei - $windows_hei ) / 2),$windows_wid,$windows_hei
+	wmctrl -r $windwos_name -e 2,$(expr $(expr $wid - $windows_wid) / 2),$(expr $(expr $hei - $windows_hei) / 2),$windows_wid,$windows_hei
 }
 
-
-usage (){
+usage() {
 	echo "Usage :  $(basename "$0") [options] [--] argument-1 argument-2
 
 	Options:
@@ -167,32 +179,44 @@ usage (){
 
 while getopts ":hp:vlruijktdcMw:D:-:" opt; do
 	case "${opt}" in
-		h) usage && exit 0;;
-		p) second_screen="${OPTARG}";;
-		v) echo "$0 -- Version $ScriptVersion"; exit ;;
-		l) key="left";;
-		r) key="right";;
-		u) key="u";;
-		i) key="i";;
-		j) key="j";;
-		k) key="k";;
-		t) key="top";;
-		d) key="down";;
-		c) key="center";;
-		M) key="Max";;
-		w) windwos_name="${OPTARG}";;
-		D) directory=${OPTARG};;
-		-) case "${OPTARG}" in
-			help) usage && exit 0;;
-			version)    echo "$0 -- Version $ScriptVersion"; exit ;;
-			file)       file=${!OPTIND}; OPTIND=$((OPTIND+1));;
-			directory)  directory=${!OPTIND}; OPTIND=$((OPTIND+1));;
-			*)          echo "Invalid option: --${OPTARG}" >&2 && exit 1;;
-		esac;;
-	:) echo "Option -${OPTARG} requires an argument." >&2 && exit 1;;
-	*) echo "Invalid option: -${OPTARG}" >&2 && exit 1;;
-esac
+	h) usage && exit 0 ;;
+	p) second_screen="${OPTARG}" ;;
+	v)
+		echo "$0 -- Version $ScriptVersion"
+		exit
+		;;
+	l) key="left" ;;
+	r) key="right" ;;
+	u) key="u" ;;
+	i) key="i" ;;
+	j) key="j" ;;
+	k) key="k" ;;
+	t) key="top" ;;
+	d) key="down" ;;
+	c) key="center" ;;
+	M) key="Max" ;;
+	w) windwos_name="${OPTARG}" ;;
+	D) directory=${OPTARG} ;;
+	-) case "${OPTARG}" in
+		help) usage && exit 0 ;;
+		version)
+			echo "$0 -- Version $ScriptVersion"
+			exit
+			;;
+		file)
+			file=${!OPTIND}
+			OPTIND=$((OPTIND + 1))
+			;;
+		directory)
+			directory=${!OPTIND}
+			OPTIND=$((OPTIND + 1))
+			;;
+		*) echo "Invalid option: --${OPTARG}" >&2 && exit 1 ;;
+		esac ;;
+	:) echo "Option -${OPTARG} requires an argument." >&2 && exit 1 ;;
+	*) echo "Invalid option: -${OPTARG}" >&2 && exit 1 ;;
+	esac
 done
-shift $((OPTIND-1))
+shift $((OPTIND - 1))
 
 main "$@"
