Auto commit from[/usr/local/bin/save-work]

diff --git a/tools/vimm b/tools/vimm
--- a/tools/vimm
+++ b/tools/vimm
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+set -e
+
+TMP=/tmp
+vim=vim
+#vim=nvim
+
 file="$@"
 #  如果只是输入了vimm则进入判断 #
 if [ "$file" == "" ]; then
@@ -14,11 +20,17 @@ if [ "$file" == "" ]; then
 	fi
 fi
 
-if [ ! -f $HOME/.config/nvim/init.vim ]; then
-	echo -e "\033[31mNot found the $HOME/.config/nvim/init.vim\033[0m"
+if [ $vim == "nvim" ]; then
+	config_file="$HOME/.config/nvim/init.vim"
+else
+	config_file="$HOME/.vimrc"
+fi
+
+if [ ! -f $config_file ]; then
+	echo -e "\033[31mNot found the $config_file\033[0m"
 	exit
 fi
-sed 's/let g:is_vim_studio=0/let g:is_vim_studio=1/' $HOME/.config/nvim/init.vim >/tmp/init_studio.vim
+sed 's/let g:is_vim_studio=0/let g:is_vim_studio=1/' $config_file >$TMP/init_studio.vim
 
-#nvim -u /tmp/init_studio.vim -c "let \$MYVIMRC = expand('\$HOME/.config/nvim/init.vim') | execute 'lua require(\"notify\")(\"Welcome to VIM-Studio\")'" $file
-nvim -u /tmp/init_studio.vim -c "let \$MYVIMRC = expand('\$HOME/.config/nvim/init.vim')" $file
+#$vim -u $TMP/init_studio.vim -c "let \$MYVIMRC = expand('\$config_file') | execute 'lua require(\"notify\")(\"Welcome to VIM-Studio\")'" $file
+$vim -u $TMP/init_studio.vim -c "let \$MYVIMRC = expand('$config_file')" $file
